### ISSUE TITLE
TFT_IO.py Recent code breaking change in stmhal

### ISSUE THREAD

**Issue by peterhinch** [robert-hh/SSD1963-TFT-Library-for-PyBoard#2]
The constant stm.GPIO_BSRRL is now stm.GPIO_BSRR. This seems to have been done to make the name compatible with the device datasheet. Also affects the touch screen driver.

**Comment by robert-hh** [comment]
Hello Peter. Thanks for the hint. I'll check. Do you know whether the value changed?

**Comment by peterhinch** [comment]
I didn't check but I don't think it has. A simple search and replace fixes it.

**Comment by robert-hh** [comment]
Yes, that works. The values of GPIO_BSSR and GPIO_BSSRL are the same, and replace does then job. I'm just wondering If I should add code for backward compatibility.
Update: backward compatibility seems not to be possible in an easy way. There is no try/except in viper or assembly code, and no access to global symbols in assembler code.

**Comment by peterhinch** [comment]
I did assume the value was the same, otherwise it surely wouldn't work! I plan to make a note in the ugui docs requiring updated firmware. Or perhaps include a test along [these lines](https://github.com/peterhinch/micropython-samples/tree/master/buildcheck).

**Comment by robert-hh** [comment]
The only way to make it backward compatible is NOT to use the stm module for that value, but something like:
`_GPIO_BSRR = const(24)`
That works for both viper and assembler code, but it is not good either way.

**Comment by peterhinch** [comment]
See [Damien's response](http://forum.micropython.org/viewtopic.php?f=3&t=2707&sid=dacfa316d2083f3808887a69af10bdfa)

**Comment by robert-hh** [comment]
Hello Peter,
thanks. I've seen it. I will not change the definitions back, but at least the old versions will work again with the newest firmware.
Robert

**Comment by peterhinch** [comment]
Agreed. I'll close this now.

Regards, Pete
